Corrected import for when the library is installed
When installing the library using

    python setup.py install
    
    >>> import Adafruit_Nokia_LCD as LCD
    [...]
        File "__init__.py", line 1 in <module>
    ImportError: No module named 'PCD8544'

The module PCD8544 cannot be found because it is part of package Adafruit_Nokia_LCD. The import line in file __init__.py should use the following relative import

    from .PCD8544 import *

as proposed in this PR.